"""
evaluate_pipeline.py
--------------------
Offline RAGAS 0.4.x evaluation of the RAG pipeline.
Run independently — NOT from inside Streamlit.

Usage
-----
    python evaluate_pipeline.py --pdf path/to/your.pdf
    python evaluate_pipeline.py --pdf report.pdf --questions "Q1" "Q2" "Q3"

RAGAS 0.4.x API
---------------
- Metrics from ragas.metrics.collections; instantiated with Faithfulness(llm=...)
- LLM via llm_factory(model, client=AsyncOpenAI(..., base_url=groq)) — LangchainLLMWrapper deprecated
- provider="groq" with native Groq client is broken (RAGAS adapter calls .messages, Groq SDK uses .chat.completions)
- Embeddings via ragas.embeddings.HuggingFaceEmbeddings — native, no wrapper needed
- evaluate() deprecated in 0.4.x; replaced with per-sample metric.ascore(**kwargs)
- ascore() returns MetricResult with .value (float)

Ground truth
------------
Reference answers generated by a separate LLM call (temperature=0) grounded
in retrieved chunks only — NOT the pipeline's own answer. This makes
ContextRecall a meaningful signal rather than self-referential scoring.

Output
------
    results/ragas_scores.csv    — per-question scores
    results/ragas_summary.json  — aggregated means + pipeline config snapshot
"""

import argparse
import asyncio
import json
import logging
import time
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from config import cfg  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

DEFAULT_EVAL_QUESTIONS = [
    "What is the main topic of this document?",
    "What are the key findings or conclusions presented?",
    "Who are the authors or stakeholders mentioned?",
    "What methodology or approach is described?",
    "What recommendations or next steps are proposed?",
]

_GT_SYSTEM_PROMPT = (
    "You are a precise factual assistant. "
    "Given a context and a question, produce a concise reference answer "
    "using ONLY information present in the context. "
    "If the answer is not in the context, respond with: "
    "'The answer is not available in the provided document.'"
)

# ---------------------------------------------------------------------------
# Ground-truth generation
# ---------------------------------------------------------------------------

def _generate_reference(context: str, question: str, sync_groq_client) -> str:
    """
    Generate a reference answer via a separate LLM call with temperature=0.
    Decoupled from pipeline output — prevents self-referential RAGAS scoring.
    """
    response = sync_groq_client.chat.completions.create(
        model=cfg.llm_model,
        messages=[
            {"role": "system", "content": _GT_SYSTEM_PROMPT},
            {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {question}"},
        ],
        max_tokens=512,
        temperature=0.0,
    )
    return response.choices[0].message.content.strip()


# ---------------------------------------------------------------------------
# Dataset builder
# ---------------------------------------------------------------------------

def build_eval_samples(rag_chain, questions: list[str], sync_groq_client) -> list[dict]:
    """
    Run each question through the RAG chain and generate a reference answer.
    Returns list of dicts: user_input, response, retrieved_contexts, reference.
    """
    samples = []
    for i, question in enumerate(questions):
        logger.info("[%d/%d] %s", i + 1, len(questions), question[:70])

        chain_output = rag_chain.invoke({"query": question})
        answer: str = chain_output["result"]
        contexts: list[str] = [doc.page_content for doc in chain_output["source_documents"]]

        combined_context = "\n\n".join(contexts)
        reference = _generate_reference(combined_context, question, sync_groq_client)

        samples.append({
            "user_input": question,
            "response": answer,
            "retrieved_contexts": contexts,
            "reference": reference,
        })

        if i < len(questions) - 1:
            time.sleep(3)  # Two LLM calls per question; respect Groq rate limits.

    return samples


# ---------------------------------------------------------------------------
# RAGAS 0.4.x evaluator
# ---------------------------------------------------------------------------

def _build_ragas_llm():
    """
    Build RAGAS-native LLM via llm_factory() with AsyncOpenAI + Groq base URL.

    llm_factory() is the RAGAS 0.4.x recommended approach (LangchainLLMWrapper
    is deprecated). The native Groq client (provider="groq") is documented by
    RAGAS but is broken in practice: RAGAS's Instructor adapter calls
    client.messages.create, but the Groq SDK exposes client.chat.completions —
    causing AttributeError: 'Groq' object has no attribute 'messages'.

    AsyncOpenAI with a Groq base_url works correctly because RAGAS routes it
    through the OpenAI Instructor adapter which uses client.chat.completions.
    """
    from openai import AsyncOpenAI
    from ragas.llms import llm_factory

    async_groq_client = AsyncOpenAI(
        api_key=cfg.groq_api_key,
        base_url="https://api.groq.com/openai/v1",
    )
    return llm_factory(cfg.llm_model, client=async_groq_client)


def _build_ragas_embeddings():
    """
    Build RAGAS-native HuggingFace embeddings.
    ragas.embeddings.HuggingFaceEmbeddings is the 0.4.x native class.
    LangchainEmbeddingsWrapper is deprecated in 0.4.x.
    """
    from ragas.embeddings import HuggingFaceEmbeddings as RagasHFEmbeddings
    return RagasHFEmbeddings(model=cfg.embedding_model)


async def _score_all_samples(
    samples: list[dict],
    ragas_llm,
    ragas_embeddings,
    per_sample_timeout: float = 120.0,
) -> list[dict]:
    """
    Score each sample with Faithfulness, AnswerRelevancy, ContextRecall.

    Uses RAGAS 0.4.x metric.ascore(**kwargs) pattern.
    Each metric call is wrapped in asyncio.wait_for with a per-sample timeout
    to prevent indefinite hangs on network issues or Groq outages.
    """
    from ragas.metrics.collections import AnswerRelevancy, ContextRecall, Faithfulness

    faithfulness_metric = Faithfulness(llm=ragas_llm)
    relevancy_metric = AnswerRelevancy(llm=ragas_llm, embeddings=ragas_embeddings)
    recall_metric = ContextRecall(llm=ragas_llm)

    results = []
    for i, sample in enumerate(samples):
        logger.info("Scoring sample %d/%d…", i + 1, len(samples))
        row: dict = {"user_input": sample["user_input"]}

        for metric, name, kwargs in [
            (
                # Faithfulness: user_input + response + retrieved_contexts
                faithfulness_metric, "faithfulness",
                {
                    "user_input": sample["user_input"],
                    "response": sample["response"],
                    "retrieved_contexts": sample["retrieved_contexts"],
                },
            ),
            (
                # AnswerRelevancy: user_input + response ONLY — no retrieved_contexts
                relevancy_metric, "answer_relevancy",
                {
                    "user_input": sample["user_input"],
                    "response": sample["response"],
                },
            ),
            (
                # ContextRecall: user_input + retrieved_contexts + reference — no response
                recall_metric, "context_recall",
                {
                    "user_input": sample["user_input"],
                    "retrieved_contexts": sample["retrieved_contexts"],
                    "reference": sample["reference"],
                },
            ),
        ]:
            try:
                result = await asyncio.wait_for(
                    metric.ascore(**kwargs),
                    timeout=per_sample_timeout,
                )
                row[name] = round(float(result.value), 4)
            except asyncio.TimeoutError:
                logger.error("%s scoring timed out after %.0fs for sample %d.",
                             name, per_sample_timeout, i + 1)
                row[name] = None
            except Exception:
                logger.exception("%s scoring failed for sample %d.", name, i + 1)
                row[name] = None

        results.append(row)
        if i < len(samples) - 1:
            time.sleep(2)  # Sequential scoring — avoid parallel Groq 429s.

    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run_evaluation(pdf_path: str, questions: list[str]) -> None:
    import pandas as pd
    from openai import OpenAI

    from pipeline import build_pipeline, get_doc_hash, get_embeddings

    # ── 1. Load embeddings once — passed to build_pipeline to avoid re-download
    logger.info("[1/5] Loading embedding model…")
    embeddings = get_embeddings()

    # ── 2. RAG chain ──────────────────────────────────────────────────────────
    logger.info("[2/5] Loading RAG pipeline…")
    with open(pdf_path, "rb") as f:
        file_bytes = f.read()
    rag_chain, _ = build_pipeline(pdf_path, get_doc_hash(file_bytes), embeddings)

    # ── 3. Sync Groq client for reference generation ──────────────────────────
    sync_groq_client = OpenAI(
        api_key=cfg.groq_api_key,
        base_url="https://api.groq.com/openai/v1",
    )

    # ── 4. Run chain + generate references ───────────────────────────────────
    logger.info("[3/5] Running %d questions + generating references…", len(questions))
    samples = build_eval_samples(rag_chain, questions, sync_groq_client)

    # ── 5. Build RAGAS 0.4.x evaluator ───────────────────────────────────────
    logger.info("[4/5] Initialising RAGAS 0.4.x evaluator…")
    ragas_llm = _build_ragas_llm()
    ragas_embeddings = _build_ragas_embeddings()

    # ── 6. Score with timeout guard ───────────────────────────────────────────
    logger.info("[5/5] Scoring with RAGAS (sequential, ~3–5 min)…")
    try:
        scored_rows = asyncio.run(
            asyncio.wait_for(
                _score_all_samples(samples, ragas_llm, ragas_embeddings),
                timeout=600.0,  # 10 min hard ceiling for the full evaluation run
            )
        )
    except asyncio.TimeoutError:
        logger.error("Evaluation exceeded 10-minute global timeout. Partial results may be saved.")
        raise

    # ── 7. Display ────────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("RAGAS 0.4.x EVALUATION RESULTS")
    print("=" * 60)

    df = pd.DataFrame(scored_rows)
    print(df.to_string(index=False))

    metric_cols = ["faithfulness", "answer_relevancy", "context_recall"]
    summary: dict = {}
    for col in metric_cols:
        if col in df.columns:
            valid = df[col].dropna()
            summary[col] = round(float(valid.mean()), 4) if len(valid) > 0 else None
            if summary[col] is None:
                print(f"WARNING: {col} had no successful scores — likely rate-limit or timeout.")

    summary["n_questions"] = len(questions)
    summary["pdf"] = pdf_path
    summary["chunk_size"] = cfg.chunk_size
    summary["chunk_overlap"] = cfg.chunk_overlap
    summary["retriever_k"] = cfg.retriever_k
    summary["llm_temperature"] = cfg.llm_temperature

    print("\nAggregate scores (mean across all questions):")
    for k, v in summary.items():
        if isinstance(v, float):
            print(f"  {k:<25} {v:.4f}")

    # ── 8. Persist ────────────────────────────────────────────────────────────
    output_dir = Path("results")
    output_dir.mkdir(exist_ok=True)

    csv_path = output_dir / "ragas_scores.csv"
    json_path = output_dir / "ragas_summary.json"

    df.to_csv(csv_path, index=False)
    with open(json_path, "w") as f:
        json.dump(summary, f, indent=2)

    print(f"\nPer-question breakdown : {csv_path}")
    print(f"Aggregate summary      : {json_path}")
    print("\n" + "-" * 60)
    print("Score interpretation (0–1, higher = better):")
    print("  faithfulness     > 0.80  → answers grounded in context")
    print("  answer_relevancy > 0.80  → answers on-topic")
    print("  context_recall   > 0.70  → retriever surfacing right chunks")
    print("\nTuning: edit config.py (chunk_size, retriever_k, llm_temperature)")
    print("and re-run to compare results across configurations.")
    print("-" * 60)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate the RAG pipeline with RAGAS 0.4.x.")
    parser.add_argument("--pdf", required=True, help="Path to the PDF to evaluate against.")
    parser.add_argument("--questions", nargs="+", default=None, help="Custom eval questions.")
    args = parser.parse_args()

    run_evaluation(
        pdf_path=args.pdf,
        questions=args.questions if args.questions else DEFAULT_EVAL_QUESTIONS,
    )
